const characterTypes = [
	{ type: "Human", example: "Luke Skywalker" },
	{ type: "Twi'lek", example: "Aayla Secura" },
	{ type: "Wookiee", example: "Chewbacca" },
	{ type: "Rodian", example: "Greedo" },
	{ type: "Jedi", example: "Yoda" },
	{ type: "Sith", example: "Darth Vader" },
	{ type: "Droid", example: "R2-D2" },
	{ type: "Droid", example: "C-3PO" },
	{ type: "Ewok", example: "Wicket" },
	{ type: "Mandalorian", example: "Din Djarin" },
	{ type: "Clone Trooper", example: "Captain Rex" },
	{ type: "Bounty Hunter", example: "Boba Fett" },
	{ type: "Smuggler", example: "Han Solo" },
	{ type: "Hutt", example: "Jabba the Hutt" },
	{ type: "Nautolan", example: "Kit Fisto" },
	{ type: "Chiss", example: "Thrawn" },
	{ type: "Mon Calamari", example: "Admiral Ackbar" },
	{ type: "Togruta", example: "Ahsoka Tano" },
	{ type: "Zabrak", example: "Darth Maul" },
	{ type: "Tusken Raider", example: "Sharad Hett" },
	{ type: "Gungan", example: "Jar Jar Binks" },
];

export default characterTypes;
