const storySettings = {
	locations: [
		"Ahch-To",
		"Alderaan",
		"Bespin",
		"Coruscant",
		"Dagobah",
		"Dathomir",
		"Endor",
		"Geonosis",
		"Hoth",
		"Jakku",
		"Jedha",
		"Kamino",
		"Kashyyyk",
		"Lothal",
		"Mandalore",
		"Mustafar",
		"Naboo",
		"Scarif",
		"Tatooine",
		"Yavin 4",
	],
	timePeriods: [
		"Old Republic Era",
		"High Republic Era",
		"Mandalorian Wars",
		"Fall of the Jedi",
		"Clone Wars",
		"Jedi Purge",
		"Reign of the Empire",
		"Battle of Scarif",
		"Battle of Yavin",
		"Galactic Civil War",
		"Battle of Hoth",
		"Battle of Endor",
		"Age of Rebellion",
		"Fall of Mandalore",
		"Rise of the First Order",
		"Starkiller Incident",
		"Rise of Skywalker",
		"New Republic Era",
		"Post-Galactic Civil War",
		"Siege of Mandalore",
	],
	plotThemes: [
		"Ancestral Mystery",
		"Balance of the Force",
		"Betrayal within the Ranks",
		"Clash of Civilizations",
		"Conflict between Light and Dark",
		"Corruption of Power",
		"Creation of the Clone Army",
		"Defending the Weak",
		"Destruction of the Death Star",
		"Fall of a Hero",
		"Forbidden Love",
		"Hero's Journey",
		"Identity Crisis",
		"Imperial Domination",
		"Intergalactic Diplomacy",
		"Journey of Redemption",
		"Lost and Found",
		"Rebellion against Tyranny",
		"Rise of the Empire",
		"Secret Rebel Missions",
		"Search for the Truth",
		"Survival on Hostile Planets",
		"The Chosen One Prophecy",
		"The Great Hyperspace War",
		"The Mandalorian Quest",
		"The Rise of a Sith Lord",
		"The Scourge of the Sith",
		"Tragedy of Darth Plagueis",
		"Unexpected Alliances",
		"War of the Bounty Hunters",
	],
};

export default storySettings;
