const storyElements = {
	plotTwists: [
		"An unexpected ally",
		"A betrayal from within",
		"A secret identity revealed",
		"A lost artifact is found",
		"An ancient prophecy fulfilled",
		"A double agent is uncovered",
		"A surprise attack",
		"A character switches sides",
		"A powerful weapon discovered",
		"A hidden base revealed",
	],
	moralLessons: [
		"Balancing the Force",
		"Compassion",
		"Courage",
		"Determination",
		"Empathy",
		"Forgiveness",
		"Generosity",
		"Gratitude",
		"Honesty",
		"Hope in Adversity",
		"Humility",
		"Integrity",
		"Justice",
		"Kindness",
		"Legacy of the Jedi",
		"Learning from Failure",
		"Loyalty",
		"Overcoming Fear",
		"Patience",
		"Peace over War",
		"Perseverance",
		"Redemption",
		"Respect",
		"Responsibility",
		"Sacrifice for the Greater Good",
		"Selflessness",
		"Strength in Unity",
		"Teamwork",
		"The Dangers of Anger",
		"The Importance of Mentorship",
		"The Power of Friendship",
		"The Value of Training",
		"Trustworthiness",
		"Unity in Diversity",
	],
};

export default storyElements;
