const storySettings = {
	locations: [
		"Forest",
		"Desert",
		"Mountain",
		"City",
		"Space Station",
		"Underwater",
		"Castle",
		"Village",
		"Island",
		"Cave",
		"Ancient Ruins",
		"Haunted House",
		"Abandoned Factory",
		"Magical Realm",
		"Enchanted Forest",
		"Secret Laboratory",
		"Distant Planet",
		"Royal Palace",
		"Pirate Ship",
		"Underground Bunker",
		// Add more locations here
	],
	timePeriods: [
		"Present Day",
		"Medieval",
		"Future",
		"Prehistoric",
		"Renaissance",
		"Victorian Era",
		"Roaring Twenties",
		"Dystopian Future",
		"Ancient Egypt",
		"Far Distant Future",
		"Golden Age of Piracy",
		"Industrial Revolution",
		"Age of Exploration",
		"Post-Apocalyptic",
		"Cyberpunk",
		"Stone Age",
		"Classical Antiquity",
		"Wild West",
		"Gilded Age",
		"Space Age",
		// Add more time periods here
	],
	moralLessons: [
		"Honesty",
		"Courage",
		"Perseverance",
		"Kindness",
		"Loyalty",
		"Forgiveness",
		"Humility",
		"Selflessness",
		"Responsibility",
		"Compassion",
		"Integrity",
		"Justice",
		"Empathy",
		"Respect",
		"Patience",
		"Generosity",
		"Gratitude",
		"Teamwork",
		"Determination",
		"Trustworthiness",
		// Add more moral lessons here
	],
};

export default storySettings;
