const storyElements = {
	plotTwists: [
		"Unexpected Ally",
		"Betrayal",
		"Secret Revealed",
		"Time Travel",
		"Hidden Treasure",
		"False Identity",
		"Mystery Illness",
		"Lost Memories",
		"Unexpected Rescue",
		"Natural Disaster",
		"Double Agent",
		"Sudden Disappearance",
		"Evil Twin",
		"Prophecy Fulfilled",
		"Artifact Activation",
		"Secret Passage",
		"Unlikely Hero",
		"Haunting Vision",
		"Alien Encounter",
		"Reversed Fate",
		// Add more plot twists here
	],
	moralLessons: [
		"Honesty",
		"Courage",
		"Perseverance",
		"Kindness",
		"Loyalty",
		"Forgiveness",
		"Humility",
		"Selflessness",
		"Responsibility",
		"Compassion",
		"Integrity",
		"Justice",
		"Empathy",
		"Respect",
		"Patience",
		"Generosity",
		"Gratitude",
		"Teamwork",
		"Determination",
		"Trustworthiness",
		// Add more moral lessons here
	],
};

export default storyElements;
